const latinVocab = [
    {
        principalParts: "amō, amāre, amāvī, amātus",
        meaning: "to love",
        presActPart: ["amāns, amantis"],
        perfPassPart: ["amātus, -a, -um"],
        futActPart: ["amātūrus, -a, -um", "amātūrus, -ūra, -ūrum"],
        presActInf: ["amāre"],
        presPassInf: ["amārī"],
        perfActInf: ["amāvisse"],
        perfPassInf: ["amātus, -a, -um esse", "amātus esse"],
        futActInf: ["amātūrus, -a, -um esse", "amātūrus esse"],
        futPassInf: ["amātum īrī", ""] 
    },
    {
        principalParts: "laudō, laudāre, laudāvī, laudātus",
        meaning: "to praise",
        presActPart: ["laudāns, laudantis"],
        perfPassPart: ["laudātus, -a, -um"],
        futActPart: ["laudātūrus, -a, -um", "laudātūrus, -ūra, -ūrum"],
        presActInf: ["laudāre"],
        presPassInf: ["laudārī"],
        perfActInf: ["laudāvisse"],
        perfPassInf: ["laudātus, -a, -um esse", "laudātus esse"],
        futActInf: ["laudātūrus, -a, -um esse", "laudātūrus esse"],
        futPassInf: ["laudātum īrī", ""]
    },
    {
        principalParts: "moneō, monēre, monuī, monitus",
        meaning: "to warn, advise",
        presActPart: ["monēns, monentis"],
        perfPassPart: ["monitus, -a, -um"],
        futActPart: ["monitūrus, -a, -um", "monitūrus, -ūra, -ūrum"],
        presActInf: ["monēre"],
        presPassInf: ["monērī"],
        perfActInf: ["monuisse"],
        perfPassInf: ["monitus, -a, -um esse", "monitus esse"],
        futActInf: ["monitūrus, -a, -um esse", "monitūrus esse"],
        futPassInf: ["monitum īrī", ""]
    },
    {
        principalParts: "habeō, habēre, habuī, habitus",
        meaning: "to have, hold",
        presActPart: ["habēns, habentis"],
        perfPassPart: ["habitus, -a, -um"],
        futActPart: ["habitūrus, -a, -um", "habitūrus, -ūra, -ūrum"],
        presActInf: ["habēre"],
        presPassInf: ["habērī"],
        perfActInf: ["habuisse"],
        perfPassInf: ["habitus, -a, -um esse", "habitus esse"],
        futActInf: ["habitūrus, -a, -um esse", "habitūrus esse"],
        futPassInf: ["habitum īrī", ""]
    },
    {
        principalParts: "dūcō, dūcere, dūxī, ductus",
        meaning: "to lead",
        presActPart: ["dūcēns, dūcentis"],
        perfPassPart: ["ductus, -a, -um"],
        futActPart: ["ductūrus, -a, -um", "ductūrus, -ūra, -ūrum"],
        presActInf: ["dūcere"],
        presPassInf: ["dūcī"],
        perfActInf: ["dūxisse"],
        perfPassInf: ["ductus, -a, -um esse", "ductus esse"],
        futActInf: ["ductūrus, -a, -um esse", "ductūrus esse"],
        futPassInf: ["ductum īrī", ""]
    },
    {
        principalParts: "mittō, mittere, mīsī, missus",
        meaning: "to send",
        presActPart: ["mittēns, mittentis"],
        perfPassPart: ["missus, -a, -um"],
        futActPart: ["missūrus, -a, -um", "missūrus, -ūra, -ūrum"],
        presActInf: ["mittere"],
        presPassInf: ["mittī"],
        perfActInf: ["mīsisse"],
        perfPassInf: ["missus, -a, -um esse", "missus esse"],
        futActInf: ["missūrus, -a, -um esse", "missūrus esse"],
        futPassInf: ["missum īrī", ""]
    },
    {
        principalParts: "audiō, audīre, audīvī, audītus",
        meaning: "to hear",
        presActPart: ["audiēns, audientis"],
        perfPassPart: ["audītus, -a, -um"],
        futActPart: ["audītūrus, -a, -um", "audītūrus, -ūra, -ūrum"],
        presActInf: ["audīre"],
        presPassInf: ["audīrī"],
        perfActInf: ["audīvisse"],
        perfPassInf: ["audītus, -a, -um esse", "audītus esse"],
        futActInf: ["audītūrus, -a, -um esse", "audītūrus esse"],
        futPassInf: ["audītum īrī", ""]
    },
    {
        principalParts: "capiō, capere, cēpī, captus",
        meaning: "to take, capture",
        presActPart: ["capiēns, capientis"],
        perfPassPart: ["captus, -a, -um"],
        futActPart: ["captūrus, -a, -um", "captūrus, -ūra, -ūrum"],
        presActInf: ["capere"],
        presPassInf: ["capī"],
        perfActInf: ["cēpisse"],
        perfPassInf: ["captus, -a, -um esse", "captus esse"],
        futActInf: ["captūrus, -a, -um esse", "captūrus esse"],
        futPassInf: ["captum īrī", ""]
    },
    {
        principalParts: "faciō, facere, fēcī, factus",
        meaning: "to do, make",
        presActPart: ["faciēns, facientis"],
        perfPassPart: ["factus, -a, -um"],
        futActPart: ["factūrus, -a, -um", "factūrus, -ūra, -ūrum"],
        presActInf: ["facere"],
        presPassInf: ["fierī"],
        perfActInf: ["fēcisse"],
        perfPassInf: ["factus, -a, -um esse", "factus esse"],
        futActInf: ["factūrus, -a, -um esse", "factūrus esse"],
        futPassInf: ["factum īrī", ""]
    },
    {
        principalParts: "videō, vidēre, vīdī, vīsus",
        meaning: "to see",
        presActPart: ["vidēns, videntis"],
        perfPassPart: ["vīsus, -a, -um"],
        futActPart: ["vīsūrus, -a, -um", "vīsūrus, -ūra, -ūrum"],
        presActInf: ["vidēre"],
        presPassInf: ["vidērī"],
        perfActInf: ["vīdisse"],
        perfPassInf: ["vīsus, -a, -um esse", "vīsus esse"],
        futActInf: ["vīsūrus, -a, -um esse", "vīsūrus esse"],
        futPassInf: ["vīsum īrī", ""]
    },
    {
        principalParts: "moveō, movēre, mōvī, mōtus",
        meaning: "to move",
        presActPart: ["movēns, moventis"],
        perfPassPart: ["mōtus, -a, -um"],
        futActPart: ["mōtūrus, -a, -um", "mōtūrus, -ūra, -ūrum"],
        presActInf: ["movēre"],
        presPassInf: ["movērī"],
        perfActInf: ["mōvisse"],
        perfPassInf: ["mōtus, -a, -um esse", "mōtus esse"],
        futActInf: ["mōtūrus, -a, -um esse", "mōtūrus esse"],
        futPassInf: ["mōtum īrī", ""]
    },
    {
        principalParts: "teneō, tenēre, tenuī, tentus",
        meaning: "to hold",
        presActPart: ["tenēns, tenentis"],
        perfPassPart: ["tentus, -a, -um"],
        futActPart: ["tentūrus, -a, -um", "tentūrus, -ūra, -ūrum"],
        presActInf: ["tenēre"],
        presPassInf: ["tenērī"],
        perfActInf: ["tenuisse"],
        perfPassInf: ["tentus, -a, -um esse", "tentus esse"],
        futActInf: ["tentūrus, -a, -um esse", "tentūrus esse"],
        futPassInf: ["tentum īrī", ""]
    },
    {
        principalParts: "vincō, vincere, vīcī, victus",
        meaning: "to conquer",
        presActPart: ["vincēns, vincentis"],
        perfPassPart: ["victus, -a, -um"],
        futActPart: ["victūrus, -a, -um", "victūrus, -ūra, -ūrum"],
        presActInf: ["vincere"],
        presPassInf: ["vincī"],
        perfActInf: ["vīcisse"],
        perfPassInf: ["victus, -a, -um esse", "victus esse"],
        futActInf: ["victūrus, -a, -um esse", "victūrus esse"],
        futPassInf: ["victum īrī", ""]
    },
    {
        principalParts: "agō, agere, ēgī, āctus",
        meaning: "to do, drive",
        presActPart: ["agēns, agentis"],
        perfPassPart: ["āctus, -a, -um"],
        futActPart: ["āctūrus, -a, -um", "āctūrus, -ūra, -ūrum"],
        presActInf: ["agere"],
        presPassInf: ["agī"],
        perfActInf: ["ēgisse"],
        perfPassInf: ["āctus, -a, -um esse", "āctus esse"],
        futActInf: ["āctūrus, -a, -um esse", "āctūrus esse"],
        futPassInf: ["āctum īrī", ""]
    },
    {
        principalParts: "pōnō, pōnere, posuī, positus",
        meaning: "to put, place",
        presActPart: ["pōnēns, pōnentis"],
        perfPassPart: ["positus, -a, -um"],
        futActPart: ["positūrus, -a, -um", "positūrus, -ūra, -ūrum"],
        presActInf: ["pōnere"],
        presPassInf: ["pōnī"],
        perfActInf: ["posuisse"],
        perfPassInf: ["positus, -a, -um esse", "positus esse"],
        futActInf: ["positūrus, -a, -um esse", "positūrus esse"],
        futPassInf: ["positum īrī", ""]
    },
    {
        principalParts: "sciō, scīre, scīvī, scītus",
        meaning: "to know",
        presActPart: ["sciēns, scientis"],
        perfPassPart: ["scītus, -a, -um"],
        futActPart: ["scītūrus, -a, -um", "scītūrus, -ūra, -ūrum"],
        presActInf: ["scīre"],
        presPassInf: ["scīrī"],
        perfActInf: ["scīvisse"],
        perfPassInf: ["scītus, -a, -um esse", "scītus esse"],
        futActInf: ["scītūrus, -a, -um esse", "scītūrus esse"],
        futPassInf: ["scītum īrī", ""]
    },
    {
        principalParts: "inveniō, invenīre, invēnī, inventus",
        meaning: "to find",
        presActPart: ["inveniēns, invenientis"],
        perfPassPart: ["inventus, -a, -um"],
        futActPart: ["inventūrus, -a, -um", "inventūrus, -ūra, -ūrum"],
        presActInf: ["invenīre"],
        presPassInf: ["invenīrī"],
        perfActInf: ["invēnisse"],
        perfPassInf: ["inventus, -a, -um esse", "inventus esse"],
        futActInf: ["inventūrus, -a, -um esse", "inventūrus esse"],
        futPassInf: ["inventum īrī", ""]
    },
    {
        principalParts: "dō, dare, dedī, datus",
        meaning: "to give",
        presActPart: ["dāns, dantis"],
        perfPassPart: ["datus, -a, -um"],
        futActPart: ["datūrus, -a, -um", "datūrus, -ūra, -ūrum"],
        presActInf: ["dare"],
        presPassInf: ["darī"],
        perfActInf: ["dedisse"],
        perfPassInf: ["datus, -a, -um esse", "datus esse"],
        futActInf: ["datūrus, -a, -um esse", "datūrus esse"],
        futPassInf: ["datum īrī", ""]
    },
    {
        principalParts: "portō, portāre, portāvī, portātus",
        meaning: "to carry",
        presActPart: ["portāns, portantis"],
        perfPassPart: ["portātus, -a, -um"],
        futActPart: ["portātūrus, -a, -um", "portātūrus, -ūra, -ūrum"],
        presActInf: ["portāre"],
        presPassInf: ["portārī"],
        perfActInf: ["portāvisse"],
        perfPassInf: ["portātus, -a, -um esse", "portātus esse"],
        futActInf: ["portātūrus, -a, -um esse", "portātūrus esse"],
        futPassInf: ["portātum īrī", ""]
    },
    {
        principalParts: "parō, parāre, parāvī, parātus",
        meaning: "to prepare",
        presActPart: ["parāns, parantis"],
        perfPassPart: ["parātus, -a, -um"],
        futActPart: ["parātūrus, -a, -um", "parātūrus, -ūra, -ūrum"],
        presActInf: ["parāre"],
        presPassInf: ["parārī"],
        perfActInf: ["parāvisse"],
        perfPassInf: ["parātus, -a, -um esse", "parātus esse"],
        futActInf: ["parātūrus, -a, -um esse", "parātūrus esse"],
        futPassInf: ["parātum īrī", ""]
    },
    {
        principalParts: "vocō, vocāre, vocāvī, vocātus",
        meaning: "to call",
        presActPart: ["vocāns, vocantis"],
        perfPassPart: ["vocātus, -a, -um"],
        futActPart: ["vocātūrus, -a, -um", "vocātūrus, -ūra, -ūrum"],
        presActInf: ["vocāre"],
        presPassInf: ["vocārī"],
        perfActInf: ["vocāvisse"],
        perfPassInf: ["vocātus, -a, -um esse", "vocātus esse"],
        futActInf: ["vocātūrus, -a, -um esse", "vocātūrus esse"],
        futPassInf: ["vocātum īrī", ""]
    },
    {
        principalParts: "doceō, docēre, docuī, doctus",
        meaning: "to teach",
        presActPart: ["docēns, docentis"],
        perfPassPart: ["doctus, -a, -um"],
        futActPart: ["doctūrus, -a, -um", "doctūrus, -ūra, -ūrum"],
        presActInf: ["docēre"],
        presPassInf: ["docērī"],
        perfActInf: ["docuisse"],
        perfPassInf: ["doctus, -a, -um esse", "doctus esse"],
        futActInf: ["doctūrus, -a, -um esse", "doctūrus esse"],
        futPassInf: ["doctum īrī", ""]
    },
    {
        principalParts: "regō, regere, rēxī, rēctus",
        meaning: "to rule",
        presActPart: ["regēns, regentis"],
        perfPassPart: ["rēctus, -a, -um"],
        futActPart: ["rēctūrus, -a, -um", "rēctūrus, -ūra, -ūrum"],
        presActInf: ["regere"],
        presPassInf: ["regī"],
        perfActInf: ["rēxisse"],
        perfPassInf: ["rēctus, -a, -um esse", "rēctus esse"],
        futActInf: ["rēctūrus, -a, -um esse", "rēctūrus esse"],
        futPassInf: ["rēctum īrī", ""]
    },
    {
        principalParts: "dīcō, dīcere, dīxī, dictus",
        meaning: "to say, speak",
        presActPart: ["dīcēns, dīcentis"],
        perfPassPart: ["dictus, -a, -um"],
        futActPart: ["dictūrus, -a, -um", "dictūrus, -ūra, -ūrum"],
        presActInf: ["dīcere"],
        presPassInf: ["dīcī"],
        perfActInf: ["dīxisse"],
        perfPassInf: ["dictus, -a, -um esse", "dictus esse"],
        futActInf: ["dictūrus, -a, -um esse", "dictūrus esse"],
        futPassInf: ["dictum īrī", ""]
    },
    {
        principalParts: "trahō, trahere, trāxī, tractus",
        meaning: "to drag",
        presActPart: ["trahēns, trahentis"],
        perfPassPart: ["tractus, -a, -um"],
        futActPart: ["tractūrus, -a, -um", "tractūrus, -ūra, -ūrum"],
        presActInf: ["trahere"],
        presPassInf: ["trahī"],
        perfActInf: ["trāxisse"],
        perfPassInf: ["tractus, -a, -um esse", "tractus esse"],
        futActInf: ["tractūrus, -a, -um esse", "tractūrus esse"],
        futPassInf: ["tractum īrī", ""]
    }
];