window.nouns = [
  // 1st Declension
  { id: '1-1', nominative: 'agricola', genitive: '-ae', gender: 'm', definition: 'farmer', declension: 1 },
  { id: '1-2', nominative: 'anima', genitive: '-ae', gender: 'f', definition: 'breath, soul', declension: 1 },
  { id: '1-3', nominative: 'aqua', genitive: '-ae', gender: 'f', definition: 'water', declension: 1 },
  { id: '1-4', nominative: 'āra', genitive: '-ae', gender: 'f', definition: 'altar', declension: 1 },
  { id: '1-5', nominative: 'audācia', genitive: '-ae', gender: 'f', definition: 'boldness', declension: 1 },
  { id: '1-6', nominative: 'causa', genitive: '-ae', gender: 'f', definition: 'reason, cause', declension: 1 },
  { id: '1-7', nominative: 'cōpia', genitive: '-ae', gender: 'f', definition: 'abundance, troops', declension: 1 },
  { id: '1-8', nominative: 'cūra', genitive: '-ae', gender: 'f', definition: 'care, anxiety', declension: 1 },
  { id: '1-9', nominative: 'fāma', genitive: '-ae', gender: 'f', definition: 'rumor, fame', declension: 1 },
  { id: '1-10', nominative: 'fēmina', genitive: '-ae', gender: 'f', definition: 'woman', declension: 1 },
  { id: '1-11', nominative: 'fīlia', genitive: '-ae', gender: 'f', definition: 'daughter', declension: 1 },
  { id: '1-12', nominative: 'flamma', genitive: '-ae', gender: 'f', definition: 'flame', declension: 1 },
  { id: '1-13', nominative: 'fortūna', genitive: '-ae', gender: 'f', definition: 'fortune', declension: 1 },
  { id: '1-14', nominative: 'glōria', genitive: '-ae', gender: 'f', definition: 'glory', declension: 1 },
  { id: '1-15', nominative: 'grātia', genitive: '-ae', gender: 'f', definition: 'favor, gratitude', declension: 1 },
  { id: '1-16', nominative: 'hōra', genitive: '-ae', gender: 'f', definition: 'hour', declension: 1 },
  { id: '1-17', nominative: 'īnsula', genitive: '-ae', gender: 'f', definition: 'island', declension: 1 },
  { id: '1-18', nominative: 'īra', genitive: '-ae', gender: 'f', definition: 'anger', declension: 1 },
  { id: '1-19', nominative: 'lingua', genitive: '-ae', gender: 'f', definition: 'tongue, language', declension: 1 },
  { id: '1-20', nominative: 'littera', genitive: '-ae', gender: 'f', definition: 'letter (alphabet/epistle)', declension: 1 },
  { id: '1-21', nominative: 'memoria', genitive: '-ae', gender: 'f', definition: 'memory', declension: 1 },
  { id: '1-22', nominative: 'nātūra', genitive: '-ae', gender: 'f', definition: 'nature', declension: 1 },
  { id: '1-23', nominative: 'patria', genitive: '-ae', gender: 'f', definition: 'fatherland', declension: 1 },
  { id: '1-24', nominative: 'pecūnia', genitive: '-ae', gender: 'f', definition: 'money', declension: 1 },
  { id: '1-25', nominative: 'poena', genitive: '-ae', gender: 'f', definition: 'penalty', declension: 1 },
  { id: '1-26', nominative: 'porta', genitive: '-ae', gender: 'f', definition: 'gate', declension: 1 },
  { id: '1-27', nominative: 'prōvincia', genitive: '-ae', gender: 'f', definition: 'province', declension: 1 },
  { id: '1-28', nominative: 'puella', genitive: '-ae', gender: 'f', definition: 'girl', declension: 1 },
  { id: '1-29', nominative: 'rēgīna', genitive: '-ae', gender: 'f', definition: 'queen', declension: 1 },
  { id: '1-30', nominative: 'silva', genitive: '-ae', gender: 'f', definition: 'forest', declension: 1 },
  { id: '1-31', nominative: 'terra', genitive: '-ae', gender: 'f', definition: 'earth, land', declension: 1 },
  { id: '1-32', nominative: 'turba', genitive: '-ae', gender: 'f', definition: 'crowd', declension: 1 },
  { id: '1-33', nominative: 'via', genitive: '-ae', gender: 'f', definition: 'way, street', declension: 1 },
  { id: '1-34', nominative: 'victōria', genitive: '-ae', gender: 'f', definition: 'victory', declension: 1 },
  { id: '1-35', nominative: 'vīta', genitive: '-ae', gender: 'f', definition: 'life', declension: 1 },

  // 2nd Declension
  { id: '2-1', nominative: 'ager', genitive: 'agrī', gender: 'm', definition: 'field', declension: 2 },
  { id: '2-2', nominative: 'amīcus', genitive: '-ī', gender: 'm', definition: 'friend', declension: 2 },
  { id: '2-3', nominative: 'animus', genitive: '-ī', gender: 'm', definition: 'spirit, soul', declension: 2 },
  { id: '2-4', nominative: 'annus', genitive: '-ī', gender: 'm', definition: 'year', declension: 2 },
  { id: '2-5', nominative: 'argentum', genitive: '-ī', gender: 'n', definition: 'silver, money', declension: 2 },
  { id: '2-6', nominative: 'arma', genitive: '-ōrum', gender: 'n', definition: 'arms, weapons (pl.)', declension: 2 },
  { id: '2-7', nominative: 'aurum', genitive: '-ī', gender: 'n', definition: 'gold', declension: 2 },
  { id: '2-8', nominative: 'auxilium', genitive: '-ī', gender: 'n', definition: 'help', declension: 2 },
  { id: '2-9', nominative: 'bellum', genitive: '-ī', gender: 'n', definition: 'war', declension: 2 },
  { id: '2-10', nominative: 'caelum', genitive: '-ī', gender: 'n', definition: 'sky', declension: 2 },
  { id: '2-11', nominative: 'campus', genitive: '-ī', gender: 'm', definition: 'plain, field', declension: 2 },
  { id: '2-12', nominative: 'cōnsilium', genitive: '-ī', gender: 'n', definition: 'plan', declension: 2 },
  { id: '2-13', nominative: 'deus', genitive: '-ī', gender: 'm', definition: 'god', declension: 2 },
  { id: '2-14', nominative: 'dominus', genitive: '-ī', gender: 'm', definition: 'master', declension: 2 },
  { id: '2-15', nominative: 'dōnum', genitive: '-ī', gender: 'n', definition: 'gift', declension: 2 },
  { id: '2-16', nominative: 'equus', genitive: '-ī', gender: 'm', definition: 'horse', declension: 2 },
  { id: '2-17', nominative: 'exemplum', genitive: '-ī', gender: 'n', definition: 'example', declension: 2 },
  { id: '2-18', nominative: 'factum', genitive: '-ī', gender: 'n', definition: 'deed', declension: 2 },
  { id: '2-19', nominative: 'ferrum', genitive: '-ī', gender: 'n', definition: 'iron, sword', declension: 2 },
  { id: '2-20', nominative: 'fīlius', genitive: '-iī', gender: 'm', definition: 'son', declension: 2 },
  { id: '2-21', nominative: 'gaudium', genitive: '-ī', gender: 'n', definition: 'joy', declension: 2 },
  { id: '2-22', nominative: 'gladius', genitive: '-iī', gender: 'm', definition: 'sword', declension: 2 },
  { id: '2-23', nominative: 'imperium', genitive: '-iī', gender: 'n', definition: 'command, power', declension: 2 },
  { id: '2-24', nominative: 'locus', genitive: '-ī', gender: 'm', definition: 'place', declension: 2 },
  { id: '2-25', nominative: 'lūdus', genitive: '-ī', gender: 'm', definition: 'game, school', declension: 2 },
  { id: '2-26', nominative: 'modus', genitive: '-ī', gender: 'm', definition: 'manner, way', declension: 2 },
  { id: '2-27', nominative: 'mūrus', genitive: '-ī', gender: 'm', definition: 'wall', declension: 2 },
  { id: '2-28', nominative: 'numerus', genitive: '-ī', gender: 'm', definition: 'number', declension: 2 },
  { id: '2-29', nominative: 'oculus', genitive: '-ī', gender: 'm', definition: 'eye', declension: 2 },
  { id: '2-30', nominative: 'officium', genitive: '-iī', gender: 'n', definition: 'duty', declension: 2 },
  { id: '2-31', nominative: 'oppidum', genitive: '-ī', gender: 'n', definition: 'town', declension: 2 },
  { id: '2-32', nominative: 'perīculum', genitive: '-ī', gender: 'n', definition: 'danger', declension: 2 },
  { id: '2-33', nominative: 'populus', genitive: '-ī', gender: 'm', definition: 'people', declension: 2 },
  { id: '2-34', nominative: 'praemium', genitive: '-iī', gender: 'n', definition: 'reward', declension: 2 },
  { id: '2-35', nominative: 'puer', genitive: 'puerī', gender: 'm', definition: 'boy', declension: 2 },
  { id: '2-36', nominative: 'rēgnum', genitive: '-ī', gender: 'n', definition: 'kingdom', declension: 2 },
  { id: '2-37', nominative: 'saxum', genitive: '-ī', gender: 'n', definition: 'rock', declension: 2 },
  { id: '2-38', nominative: 'servus', genitive: '-ī', gender: 'm', definition: 'slave', declension: 2 },
  { id: '2-39', nominative: 'sīgnum', genitive: '-ī', gender: 'n', definition: 'sign, standard', declension: 2 },
  { id: '2-40', nominative: 'socius', genitive: '-iī', gender: 'm', definition: 'ally', declension: 2 },
  { id: '2-41', nominative: 'somnus', genitive: '-ī', gender: 'm', definition: 'sleep', declension: 2 },
  { id: '2-42', nominative: 'studium', genitive: '-iī', gender: 'n', definition: 'eagerness', declension: 2 },
  { id: '2-43', nominative: 'tēlum', genitive: '-ī', gender: 'n', definition: 'weapon', declension: 2 },
  { id: '2-44', nominative: 'templum', genitive: '-ī', gender: 'n', definition: 'temple', declension: 2 },
  { id: '2-45', nominative: 'verbum', genitive: '-ī', gender: 'n', definition: 'word', declension: 2 },
  { id: '2-46', nominative: 'vir', genitive: 'virī', gender: 'm', definition: 'man', declension: 2 },

  // 3rd Declension
  { id: '3-1', nominative: 'aetās', genitive: 'aetātis', gender: 'f', definition: 'age', declension: 3 },
  { id: '3-2', nominative: 'amor', genitive: 'amōris', gender: 'm', definition: 'love', declension: 3 },
  { id: '3-3', nominative: 'animal', genitive: 'animālis', gender: 'n', definition: 'animal', declension: 3 },
  { id: '3-4', nominative: 'ars', genitive: 'artis', gender: 'f', definition: 'art, skill', declension: 3 },
  { id: '3-5', nominative: 'arx', genitive: 'arcis', gender: 'f', definition: 'citadel', declension: 3 },
  { id: '3-6', nominative: 'caput', genitive: 'capitis', gender: 'n', definition: 'head', declension: 3 },
  { id: '3-7', nominative: 'carmen', genitive: 'carminis', gender: 'n', definition: 'song, poem', declension: 3 },
  { id: '3-8', nominative: 'cīvis', genitive: 'cīvis', gender: 'm', definition: 'citizen', declension: 3 },
  { id: '3-9', nominative: 'cīvitās', genitive: 'cīvitātis', gender: 'f', definition: 'state', declension: 3 },
  { id: '3-10', nominative: 'clāmor', genitive: 'clāmōris', gender: 'm', definition: 'shout', declension: 3 },
  { id: '3-11', nominative: 'cōnsul', genitive: 'cōnsulis', gender: 'm', definition: 'consul', declension: 3 },
  { id: '3-12', nominative: 'corpus', genitive: 'corporis', gender: 'n', definition: 'body', declension: 3 },
  { id: '3-13', nominative: 'crīmen', genitive: 'crīminis', gender: 'n', definition: 'crime, charge', declension: 3 },
  { id: '3-14', nominative: 'dolor', genitive: 'dolōris', gender: 'm', definition: 'pain', declension: 3 },
  { id: '3-15', nominative: 'dux', genitive: 'ducis', gender: 'm', definition: 'leader', declension: 3 },
  { id: '3-16', nominative: 'fīnis', genitive: 'fīnis', gender: 'm', definition: 'end, boundary', declension: 3 },
  { id: '3-17', nominative: 'flūmen', genitive: 'flūminis', gender: 'n', definition: 'river', declension: 3 },
  { id: '3-18', nominative: 'frāter', genitive: 'frātris', gender: 'm', definition: 'brother', declension: 3 },
  { id: '3-19', nominative: 'gēns', genitive: 'gentis', gender: 'f', definition: 'clan, race', declension: 3 },
  { id: '3-20', nominative: 'homō', genitive: 'hominis', gender: 'm', definition: 'human being', declension: 3 },
  { id: '3-21', nominative: 'honor', genitive: 'honōris', gender: 'm', definition: 'honor', declension: 3 },
  { id: '3-22', nominative: 'hostis', genitive: 'hostis', gender: 'm', definition: 'enemy', declension: 3 },
  { id: '3-23', nominative: 'ignis', genitive: 'ignis', gender: 'm', definition: 'fire', declension: 3 },
  { id: '3-24', nominative: 'iūs', genitive: 'iūris', gender: 'n', definition: 'right, law', declension: 3 },
  { id: '3-25', nominative: 'labor', genitive: 'labōris', gender: 'm', definition: 'labor, toil', declension: 3 },
  { id: '3-26', nominative: 'lēx', genitive: 'lēgis', gender: 'f', definition: 'law', declension: 3 },
  { id: '3-27', nominative: 'lībertās', genitive: 'lībertātis', gender: 'f', definition: 'freedom', declension: 3 },
  { id: '3-28', nominative: 'lūx', genitive: 'lūcis', gender: 'f', definition: 'light', declension: 3 },
  { id: '3-29', nominative: 'mare', genitive: 'maris', gender: 'n', definition: 'sea', declension: 3 },
  { id: '3-30', nominative: 'māter', genitive: 'mātris', gender: 'f', definition: 'mother', declension: 3 },
  { id: '3-31', nominative: 'mēns', genitive: 'mentis', gender: 'f', definition: 'mind', declension: 3 },
  { id: '3-32', nominative: 'mīles', genitive: 'mīlitis', gender: 'm', definition: 'soldier', declension: 3 },
  { id: '3-33', nominative: 'mōns', genitive: 'montis', gender: 'm', definition: 'mountain', declension: 3 },
  { id: '3-34', nominative: 'mors', genitive: 'mortis', gender: 'f', definition: 'death', declension: 3 },
  { id: '3-35', nominative: 'mōs', genitive: 'mōris', gender: 'm', definition: 'custom', declension: 3 },
  { id: '3-36', nominative: 'mulier', genitive: 'mulieris', gender: 'f', definition: 'woman', declension: 3 },
  { id: '3-37', nominative: 'nōmen', genitive: 'nōminis', gender: 'n', definition: 'name', declension: 3 },
  { id: '3-38', nominative: 'nox', genitive: 'noctis', gender: 'f', definition: 'night', declension: 3 },
  { id: '3-39', nominative: 'opus', genitive: 'operis', gender: 'n', definition: 'work', declension: 3 },
  { id: '3-40', nominative: 'ōrātiō', genitive: 'ōrātiōnis', gender: 'f', definition: 'speech', declension: 3 },
  { id: '3-41', nominative: 'pars', genitive: 'partis', gender: 'f', definition: 'part', declension: 3 },
  { id: '3-42', nominative: 'pater', genitive: 'patris', gender: 'm', definition: 'father', declension: 3 },
  { id: '3-43', nominative: 'pāx', genitive: 'pācis', gender: 'f', definition: 'peace', declension: 3 },
  { id: '3-44', nominative: 'pēs', genitive: 'pedis', gender: 'm', definition: 'foot', declension: 3 },
  { id: '3-45', nominative: 'potestās', genitive: 'potestātis', gender: 'f', definition: 'power', declension: 3 },
  { id: '3-46', nominative: 'prīnceps', genitive: 'prīncipis', gender: 'm', definition: 'chief, emperor', declension: 3 },
  { id: '3-47', nominative: 'ratiō', genitive: 'ratiōnis', gender: 'f', definition: 'method, reason', declension: 3 },
  { id: '3-48', nominative: 'rēx', genitive: 'rēgis', gender: 'm', definition: 'king', declension: 3 },
  { id: '3-49', nominative: 'scelus', genitive: 'sceleris', gender: 'n', definition: 'crime', declension: 3 },
  { id: '3-50', nominative: 'sōl', genitive: 'sōlis', gender: 'm', definition: 'sun', declension: 3 },
  { id: '3-51', nominative: 'soror', genitive: 'sorōris', gender: 'f', definition: 'sister', declension: 3 },
  { id: '3-52', nominative: 'tempus', genitive: 'temporis', gender: 'n', definition: 'time', declension: 3 },
  { id: '3-53', nominative: 'timor', genitive: 'timōris', gender: 'm', definition: 'fear', declension: 3 },
  { id: '3-54', nominative: 'urbs', genitive: 'urbis', gender: 'f', definition: 'city', declension: 3 },
  { id: '3-55', nominative: 'uxor', genitive: 'uxōris', gender: 'f', definition: 'wife', declension: 3 },
  { id: '3-56', nominative: 'vēritās', genitive: 'vēritātis', gender: 'f', definition: 'truth', declension: 3 },
  { id: '3-57', nominative: 'virtūs', genitive: 'virtūtis', gender: 'f', definition: 'courage, virtue', declension: 3 },
  { id: '3-58', nominative: 'vīs', genitive: 'vīs', gender: 'f', definition: 'force', declension: 3 },
  { id: '3-59', nominative: 'vōx', genitive: 'vōcis', gender: 'f', definition: 'voice', declension: 3 },
  { id: '3-60', nominative: 'vulnus', genitive: 'vulneris', gender: 'n', definition: 'wound', declension: 3 },
];