import { Verb } from './types';

export const VERBS_LIST: Verb[] = [
  { word: 'amo', principalParts: ['amo', 'amare', 'amavi', 'amatus'], conjugation: 1, definition: 'to love' },
  { word: 'laudo', principalParts: ['laudo', 'laudare', 'laudavi', 'laudatus'], conjugation: 1, definition: 'to praise' },
  { word: 'paro', principalParts: ['paro', 'parare', 'paravi', 'paratus'], conjugation: 1, definition: 'to prepare' },
  { word: 'porto', principalParts: ['porto', 'portare', 'portavi', 'portatus'], conjugation: 1, definition: 'to carry' },
  { word: 'pugno', principalParts: ['pugno', 'pugnare', 'pugnavi', 'pugnatus'], conjugation: 1, definition: 'to fight' },
  { word: 'voco', principalParts: ['voco', 'vocare', 'vocavi', 'vocatus'], conjugation: 1, definition: 'to call' },
  { word: 'do', principalParts: ['do', 'dare', 'dedi', 'datus'], conjugation: 1, definition: 'to give' },
  { word: 'sto', principalParts: ['sto', 'stare', 'steti', 'status'], conjugation: 1, definition: 'to stand' },
  { word: 'iuvo', principalParts: ['iuvo', 'iuvare', 'iuvi', 'iutus'], conjugation: 1, definition: 'to help' },
  { word: 'moneo', principalParts: ['moneo', 'monere', 'monui', 'monitus'], conjugation: 2, definition: 'to warn' },
  { word: 'habeo', principalParts: ['habeo', 'habere', 'habui', 'habitus'], conjugation: 2, definition: 'to have' },
  { word: 'teneo', principalParts: ['teneo', 'tenere', 'tenui', 'tentus'], conjugation: 2, definition: 'to hold' },
  { word: 'moveo', principalParts: ['moveo', 'movere', 'movi', 'motus'], conjugation: 2, definition: 'to move' },
  { word: 'video', principalParts: ['video', 'videre', 'vidi', 'visus'], conjugation: 2, definition: 'to see' },
  { word: 'iubeo', principalParts: ['iubeo', 'iubere', 'iussi', 'iussus'], conjugation: 2, definition: 'to order' },
  { word: 'augeo', principalParts: ['augeo', 'augere', 'auxi', 'auctus'], conjugation: 2, definition: 'to increase' },
  { word: 'duco', principalParts: ['duco', 'ducere', 'duxi', 'ductus'], conjugation: 3, definition: 'to lead' },
  { word: 'mitto', principalParts: ['mitto', 'mittere', 'misi', 'missus'], conjugation: 3, definition: 'to send' },
  { word: 'rego', principalParts: ['rego', 'regere', 'rexi', 'rectus'], conjugation: 3, definition: 'to rule' },
  { word: 'scribo', principalParts: ['scribo', 'scribere', 'scripsi', 'scriptus'], conjugation: 3, definition: 'to write' },
  { word: 'pono', principalParts: ['pono', 'ponere', 'posui', 'positus'], conjugation: 3, definition: 'to put, place' },
  { word: 'vinco', principalParts: ['vinco', 'vincere', 'vici', 'victus'], conjugation: 3, definition: 'to conquer' },
  { word: 'ago', principalParts: ['ago', 'agere', 'egi', 'actus'], conjugation: 3, definition: 'to do, drive' },
  { word: 'capio', principalParts: ['capio', 'capere', 'cepi', 'captus'], conjugation: '3io', definition: 'to take' },
  { word: 'facio', principalParts: ['facio', 'facere', 'feci', 'factus'], conjugation: '3io', definition: 'to make, do' },
  { word: 'iacio', principalParts: ['iacio', 'iacere', 'ieci', 'iactus'], conjugation: '3io', definition: 'to throw' },
  { word: 'audio', principalParts: ['audio', 'audire', 'audivi', 'auditus'], conjugation: 4, definition: 'to hear' },
  { word: 'venio', principalParts: ['venio', 'venire', 'veni', 'ventus'], conjugation: 4, definition: 'to come' },
  { word: 'invenio', principalParts: ['invenio', 'invenire', 'inveni', 'inventus'], conjugation: 4, definition: 'to find' },
  { word: 'sentio', principalParts: ['sentio', 'sentire', 'sensi', 'sensus'], conjugation: 4, definition: 'to feel' }
];